# Generated by Django 3.2.7 on 2021-09-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_status',
            new_name='status',
        ),
    ]
